format = """
[](#2b0076)\
$username\
[](bg:#221482 fg:#2b0076)\
$directory\
[](fg:#221482 bg:#19288e)\
$git_branch\
$git_status\
[](fg:#19288e bg:#103c9a)\
$nodejs\
[](fg:#103c9a bg:#0750a6)\
$docker_context\
[](fg:#0750a6)\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](#2b0076)"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#2b0076 fg:#ffffff"
style_root = "bg:#2b0076 fg:#ffffff"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#221482 fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[cmd_duration]
format = "[◄ $duration ](italic white)"
min_time = 0


# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "
style = "bg:#0750a6 fg:#ffffff"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#19288e fg:#ffffff"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#19288e fg:#ffffff"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:#103c9a fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "bg:#0064b2 fg:#ffffff"
format = '[ ♥ $time ]($style)'
